# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Bari 2017"
# email: "mikelantonio.trizio@gmail.com"
description: "GDG DevFest Bari 2017"
baseurl: ""
url: "https://gdgbari.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-55641503-2"
googleAnalyticsSiteUrl: "gdgbari.org"
# siteVerification: "TODO: ANALYTICS VERIFICATION ID HERE"

# Organizer Info
organizerName: "GDG Bari"
organizerAlternateName: "Google Developer Group Bari"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
# organizerEmail: "mikelantonio.trizio@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgbari.org"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, bari"
twitterAccount: "@gdg"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/forms/FcICiuS8RFz63pJm2"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Programma"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistica"}
 - {permalink: "/#tickets", text: "Biglietti"}
 # TODO: Add Hackathon
 - {link: "https://hack.developers.italia.it/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "http://gdgbari.org/schedule/", text: "Guarda il programma"}
 - {link: "https://www.eventbrite.it/e/biglietti-devfest-bari-2017-37804774097", text: "Prendi il tuo biglietto"}
rightNavigationButtons:
 - {link: "http://gdgbari.org/schedule/", text: "Guarda il programma"}
 - {link: "https://www.eventbrite.it/e/biglietti-devfest-bari-2017-37804774097", text: "Prendi il tuo biglietto"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout>"
eventDate: "6-7-8 ottobre 2017"
typeoutTextValues: '"", "Bari", "Season"'
typeoutFallback: "Bari"
heroButtons:
 - {link: "http://gdgbari.org/schedule/", text: "Guarda il programma"}
 - {permalink: "/#tickets", text: "Prendi il tuo biglietto"}
 - {link: "https://www.facebook.com/GDGBari/", text: "Seguici su Facebook"}

# About Block
aboutTitle: "Cos'è la DevFest?"
aboutBlock:
 - {title: "Conferenza", image: "conference.jpg", text: "L'appuntamento di Bari del più grande evento legato alle tecnologie di Google creato con cura artigianale per voi dalla comunità del GDG Bari! Grandi speaker e divertimento!" }
 - {title: "Sessioni", image: "workshop.jpg", text: "Una intera giornata di talk, esperienza sul campo, hacking and debugging. Vieni ed assapora la tua tecnologia preferita!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Una giornata intera di hackaton free-style! Metti insieme il tuo team e partecipa al hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
# - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "72", specialCharacter: "+", info: "ore", detail: "di pura Googliness"}
# TODO: ADD SPEAKERS COUNT HERE
# - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "+", info: "sessioni parallele", detail: "tecniche e pratiche"}

# Latest News Block
latestNewsTitle: "Ultime news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 6
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Politecnico di Bari"
eventLocationLink: "http://www.poliba.it/"
eventStreetAddress: "Via Edoardo Orabona,4"
eventAddressLocality: "Bari"
eventAddressLocalityRegion: "Puglia"
eventPostalCode: "70126"
eventAddressCountry: "Italia"
#eventStartTime: "2017-10-06T09:00"
#eventDoorTime: "09:00"
#eventEndTime: "2017-10-08T20:00"
eventPlaceCoordinates: "41.109048, 16.8783749"
mapCenterCoordinates: "41.109048, 16.8783749"
mapMobileCenterCoordinates: "41.109048, 16.8783749"

# Venue Block
venueBlockTitle: "Dove"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Politecnico di Bari"
venueFeatures: ["Il Politecnico di Bari è un’Università pubblica italiana nata nel 1990 con lo scopo di rappresentare un polo di eccellenza internazionale finalizzato al progresso culturale, scientifico e tecnologico."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "What's Up?"
twitterHashTag: "dfba17"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Stay tuned :)"
subscribeAction: "https://facebook.com/GDGBari/"
subscribeInfo: "Seguici su Facebook per più informationi sull'evento!"

# Tickets Block
ticketsTitle: "Biglietti"
ticketsInfo: ""
#ticketsOffers:
# -
#  name: "Early Bird"
#  price: "350"
#  priceCurrency: "UAH"
#  ticketsNumber: "150"
#  ribbon: "-5%"
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-25T10:00"
#  validThrough: "2014-09-30T23:59"
#-
#  name: "Last Chance"
#  price: "450"
#  priceCurrency: "UAH"
#  ticketsNumber: "100"
#  ribbon: "-20%"
#  featured: true
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-10-01T00:00"
#  validThrough: "2014-10-23T23:59"
#  disabled: true
# -
#  name: "Student"
#  price: "200"
#  priceCurrency: "UAH"
#  ticketsNumber: "50"
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-23T23:59"
#  soldOut: true
#  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+GDGBari", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGBari", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Link utili"
  links:
#   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contatti"
  links:
   - {link: "https://facebook.com/GDGBari", text: "Contattaci su Facebook"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "dfba17"

# Speakers List Block
# TODO: Set to true after Speakers page is complete
showSessions: false

# Team Block
teamBlockTitle: "Su di noi"
aboutUs: "I Google Developer Group (GDG) sono gruppi di persone interessate allo sviluppo delle tecnologie Google. I GDG sono formati principalmente da sviluppatori e utenti che sono interessati allo sviluppo o all'utilizzo delle tecnologie Google per i propri progetti.
Data, Making, Business è la tagline del GDG Bari che sperimenta le tecnologie di Big G in questi tre ambiti (che spesso si fondono tra di loro) per aiutare gli sviluppatori a migliorarsi.
Il GDG Bari è un gruppo aperto, dai neofiti agli hacker con la H maiuscola, se sei curioso, vuoi imparare e condividere idee, tecnologie o progetti, e ti trovi in Puglia questo è il gruppo che fa per te."

# Logistics Find Way Block
findWayTitle: "Come arrivare"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Trova voli"
logisticsMapCenterCoordinates: "41.109048, 16.8783749"
logisticsMapMobileCenterCoordinates: "41.109048, 16.8783749"
logisticsMapAutoDirections: true

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Politecnico di Bari"
directionDetailsCards:
 - {title: "Dall'aeroporto", information: 'Dall&#39;aeroporto di Bari - Palese è possibile raggiungere la stazione centrale sfruttando la metro o con la linea urbana 16.'}
 - {title: "Mezzi pubblici", information: 'Da piazza A. Moro si possono prendere le linee numero 21 o 22. La prima, passando per via P. Petroni, via Carulli, piazza Luigi di Savoia, via Capruzzi, via Lattanzio, via M. Cristina di Savoia, giunge in via Re David dove è possibile scendere in prossimità dell&#39;ingresso B del Campus. La seconda, attraversando via P. Petroni, via Carulli, piazza Luigi di Savoia, via Capruzzi, via Lattanzio e via Postiglione consente di arrivare su via Amendola in prossimità delle entrate C e D del campus.'}
 - {title: "Hotel", information: 'Siamo convenzionati con Hotel Campus'}
# directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
